# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peering_coord/api/info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='peering_coord/api/info.proto',
  package='coord.api',
  syntax='proto3',
  serialized_options=b'Z7github.com/netsys-lab/scion-peering-client/daemon/coord',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cpeering_coord/api/info.proto\x12\tcoord.api\"6\n\x05Owner\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tlong_name\x18\x02 \x01(\t\x12\x0c\n\x04\x61sns\x18\x03 \x03(\t\",\n\x0fGetOwnerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61sn\x18\x02 \x01(\t\"\'\n\x12SearchOwnerRequest\x12\x11\n\tlong_name\x18\x01 \x01(\t2\x86\x01\n\x04Info\x12:\n\x08GetOwner\x12\x1a.coord.api.GetOwnerRequest\x1a\x10.coord.api.Owner\"\x00\x12\x42\n\x0bSearchOwner\x12\x1d.coord.api.SearchOwnerRequest\x1a\x10.coord.api.Owner\"\x00\x30\x01\x42\x39Z7github.com/netsys-lab/scion-peering-client/daemon/coordb\x06proto3'
)




_OWNER = _descriptor.Descriptor(
  name='Owner',
  full_name='coord.api.Owner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='coord.api.Owner.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='long_name', full_name='coord.api.Owner.long_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asns', full_name='coord.api.Owner.asns', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=97,
)


_GETOWNERREQUEST = _descriptor.Descriptor(
  name='GetOwnerRequest',
  full_name='coord.api.GetOwnerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='coord.api.GetOwnerRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asn', full_name='coord.api.GetOwnerRequest.asn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=143,
)


_SEARCHOWNERREQUEST = _descriptor.Descriptor(
  name='SearchOwnerRequest',
  full_name='coord.api.SearchOwnerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='long_name', full_name='coord.api.SearchOwnerRequest.long_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=184,
)

DESCRIPTOR.message_types_by_name['Owner'] = _OWNER
DESCRIPTOR.message_types_by_name['GetOwnerRequest'] = _GETOWNERREQUEST
DESCRIPTOR.message_types_by_name['SearchOwnerRequest'] = _SEARCHOWNERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Owner = _reflection.GeneratedProtocolMessageType('Owner', (_message.Message,), {
  'DESCRIPTOR' : _OWNER,
  '__module__' : 'peering_coord.api.info_pb2'
  # @@protoc_insertion_point(class_scope:coord.api.Owner)
  })
_sym_db.RegisterMessage(Owner)

GetOwnerRequest = _reflection.GeneratedProtocolMessageType('GetOwnerRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETOWNERREQUEST,
  '__module__' : 'peering_coord.api.info_pb2'
  # @@protoc_insertion_point(class_scope:coord.api.GetOwnerRequest)
  })
_sym_db.RegisterMessage(GetOwnerRequest)

SearchOwnerRequest = _reflection.GeneratedProtocolMessageType('SearchOwnerRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHOWNERREQUEST,
  '__module__' : 'peering_coord.api.info_pb2'
  # @@protoc_insertion_point(class_scope:coord.api.SearchOwnerRequest)
  })
_sym_db.RegisterMessage(SearchOwnerRequest)


DESCRIPTOR._options = None

_INFO = _descriptor.ServiceDescriptor(
  name='Info',
  full_name='coord.api.Info',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=187,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOwner',
    full_name='coord.api.Info.GetOwner',
    index=0,
    containing_service=None,
    input_type=_GETOWNERREQUEST,
    output_type=_OWNER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SearchOwner',
    full_name='coord.api.Info.SearchOwner',
    index=1,
    containing_service=None,
    input_type=_SEARCHOWNERREQUEST,
    output_type=_OWNER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INFO)

DESCRIPTOR.services_by_name['Info'] = _INFO

# @@protoc_insertion_point(module_scope)
