version: "3.7"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=peering_coord
      - POSTGRES_USER=peering_coord
      - POSTGRES_PASSWORD=peering_coord
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - redisdata:/data

  huey:
    build:
      context: ../..
      dockerfile: docker/devel/Dockerfile
    command: ./manage.py run_huey
    environment:
      - DJANGO_SETTINGS_MODULE=standalone_coord.settings.devel_postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=peering_coord
      - POSTGRES_USER=peering_coord
      - POSTGRES_PASSWORD=peering_coord
    depends_on:
      - redis

  coordinator:
    build:
      context: ../..
      dockerfile: docker/devel/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=standalone_coord.settings.devel_postgres
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=peering_coord
      - POSTGRES_USER=peering_coord
      - POSTGRES_PASSWORD=peering_coord
    depends_on:
      - db
      - redis
    volumes:
      - web-static:/peering-coord/static/:z
    ports:
      - "8000:8000"

volumes:
  postgres:
  redisdata:
  web-static:
