version: "3.7"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=peering_coord
      - POSTGRES_USER=peering_coord
      - POSTGRES_PASSWORD=peering_coord
    volumes:
      - postgres:/var/lib/postgresql/data

  gunicorn:
    build:
      context: ../..
      dockerfile: docker/devel/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=standalone_coord.settings.devel_postgres
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=peering_coord
      - POSTGRES_USER=peering_coord
      - POSTGRES_PASSWORD=peering_coord
    depends_on:
      - db
    volumes:
      - web-static:/home/coord/peering-coord/standalone_coord/static:z
    expose:
      - "8000"

  grpcserver:
    build:
      context: ../..
      dockerfile: docker/devel/Dockerfile
    command: docker/devel/grpcserver.sh
    environment:
      - DJANGO_SETTINGS_MODULE=standalone_coord.settings.devel_postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=peering_coord
      - POSTGRES_USER=peering_coord
      - POSTGRES_PASSWORD=peering_coord
    depends_on:
      - db
    expose:
      - "50051"

  caddy:
    image: caddy:latest
    depends_on:
      - gunicorn
      - grpcserver
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - web-static:/var/www/peering-coord/static:z
      - caddy-data:/data
    ports:
      - "8000:80"
      - "50051:50051"

volumes:
  postgres:
  web-static:
  caddy-data:
